# Generated by Django 3.2.9 on 2021-12-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20211206_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
