# Generated by Django 3.2.9 on 2021-12-08 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='helpTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='help',
            name='problem',
            field=models.CharField(max_length=25),
        ),
    ]
