# Generated by Django 3.2.9 on 2021-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20211208_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='company',
            field=models.CharField(default='--select--', max_length=100),
        ),
    ]
