# Generated by Django 3.2.9 on 2021-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_help_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='c_models',
            field=models.CharField(default='model name', max_length=25),
        ),
    ]
