# Generated by Django 3.2.9 on 2021-12-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_help_c_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='c_models',
            new_name='c_model',
        ),
    ]
