# Generated by Django 3.2.9 on 2021-12-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_rename_c_models_help_c_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='problem',
            new_name='issue',
        ),
    ]
