# Generated by Django 3.2.9 on 2021-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_rename_problem_help_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='o_issue',
            field=models.CharField(default='o_issue', max_length=25),
        ),
        migrations.AlterField(
            model_name='help',
            name='issue',
            field=models.CharField(default='others', max_length=25),
        ),
    ]
