# Generated by Django 3.2.9 on 2021-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20211209_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='o_issue',
            field=models.CharField(blank='True', max_length=25),
        ),
    ]
