# Generated by Django 3.2.9 on 2022-01-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_help_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='phone',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
