# Generated by Django 3.2.9 on 2022-01-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_help_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='phone',
            field=models.IntegerField(default='number', null=True),
        ),
    ]
